### ISSUE TITLE
iframe permissions

### ISSUE THREAD

**Issue by MokhtarAkle** [fatihg61/the-startup-responsive-interactieve-website#5]
Is het nodig om de microfoon, geolocation en de camera toe te staan voor je form?

https://github.com/fatihg61/the-startup-responsive-interactieve-website/blob/88d17d150d29b96e1baceedc99bdece980184d00/form.html#L49

**Comment by fatihg61** [comment]
Dat is afkomstig van de third party form. Dat zal ik laten veranderen.
